[project]
name = "pdu-area-optimizer"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bernat Ibáñez Martínez <personal@bibanez.xyz>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.4,<3.13"
matplotlib = ">=3.8.4,<3.9"
pandas = ">=2.2.2,<2.3"
